- sections:
  - title: Getting Started
    link: docs/getting-started.md
    open: true
    articles:
    - title: Online Payments
      link: docs/GettingStarted/OnlineStoreIntegration/OnlineStoreIntegration.md
    - title: Recurring Payments
      link: docs/GettingStarted/RecurringPayments/RecurringPayments.md
