toc:
  - section:
    - title: Getting Started
    - link: getting-started.md
    - open: true
    - article:
      - title: Online Payments
      - link: GettingStarted/OnlineStoreIntegration/OnlineStoreIntegration.md
    - article:
      - title: Recurring Payments
      - link: GettingStarted/RecurringPayments/RecurringPayments.md
