- sections:
  - title: Getting Started
    link: getting-started.md
    open: true
    articles:
    - title: Online Payments
      link: GettingStarted/OnlineStoreIntegration/OnlineStoreIntegration.md
    - title: Recurring Payments
      link: GettingStarted/RecurringPayments/RecurringPayments.md
