productPage:
  - hero:
    - image: /assests/image/hero.png #???
    - descrption: Hero description
  - journey Cards:
      - journeyCard:
        - title: Learn # => learn | Learning With Pavan => learning-with-pavan
        - description: 'Use our AI-powered portal to quickly discover the right integration for your next app project.
        
        Experiment with our API’s in our intelligent API Explorer. 
        
        Browse sample code and follow our guided tutorials to learn best practices for integration.'
        - link: 
          - type: markdown
          - uri: /docs/learn.md
        - contextualNavigationCards: #cnav card
          - contextualNavigationCard:
            - title: Getting Started
            - description: Get Started with IPG.
            - link: 
              - type: markdown
              - uri: /docs/getting-started.md
          - contextualNavigationCard:
            - title: Tutorials
            - description: Learn how to integrate with IPG.
            - link: 
              - type: markdown
              - uri: /docs/tutorials.md
          - contextualNavigationCard:
            - title: Video
            - description: Watch how to create more unified commerce
            - link: 
              - type: externalLink # [externalLink | internalLink | markdown]
              - uri: https://www.youtube.com/watch?v=X8jKx8pPjrU
      - journeyCard:
        - title: Build
        - description: 'Build on top of our sample code to get your app coded in minutes.
        
        Our lightweight SDK’s and plug-in’s might be the fastest path to completing your app.'
        - link: 
          - type: markdown
          - uri: /docs/build.md
        - contextualNavigationCards:
          - contextualNavigationCard:
            - title: API Reference
            - description: Explore all our APIs
            - link: 
              - type: internalLink
              - uri: /api?type=post&path=/payments/v1/auths
          - contextualNavigationCard:
            - title: SDKs
            - description: Use SDKs to accelarate your development
            - cardType: reference | page
            - link: 
              - type: markdown
              - uri: /docs/sdks.md # => http://dev.fiserv.com/docs/api
          - contextualNavigationCard:
            - title: Sample Code
            - description: Free just like Costco samples & no limit
            - cardType: reference | page
            - link: 
              - type: markdown
              - uri: /docs/samples.md # => http://dev.fiserv.com/docs/api
      - journeyCard:
        - title: Test
        - description: 'Flex your app end-to-end in our full-featured Sandbox.
        
        Incorporate Sandbox testing into your CI pipeline.
        
        Use our intelligent Test Tracker to discover parts of your app that need more attention. 
        
        *Requires registration'
        - link: 
          - type: markdown
          - uri: docs/test.md
        - contextualNavigationCards: #cnav card
          - contextualNavigationCard:
            - title: Card Present
            - description: Use our sandbox to test your app end-to-end
            - link: 
              - type: markdown
              - uri: docs/Getting-Started/Getting-Started-CP.md
          - contextualNavigationCard:
            - title: Card Not Present
            - description: See how your app is doing
            - link: 
              - type: markdown
              - uri: docs/Getting-Started/Getting-Started-CNP.md
          - contextualNavigationCard:
            - title: Wallets
            - description: Test with confidence
            - link: 
              - type: markdown # [externalLink | internalLink | markdown]
              - uri: docs/Getting-Started/Getting-Started-Wallets.md
      - journeyCard:
        - title: Deploy
        - description: 'When your app is ready for prime time, submit it for automated certification. 
        Your certified app is now ready to be deployed to Production. 
        Congratulations!! 
        *Requires registration'
        - link: 
          - type: markdown
          - uri: /docs/deploy.md
        - contextualNavigationCards:
          - contextualNavigationCard:
            - title: Certify
            - description: Get your stamp of approval from us
            - link: 
              - type: markdown
              - uri: docs/certify.md
          - contextualNavigationCard:
            - title: Deploy
            - description: Ready, set, Deploy!
            - link: 
              - type: internalLink
              - uri: /docs/api # => http://dev.fiserv.com/docs/api
          - contextualNavigationCard:
            - title: Operate
            - description: Setup montioring and alerting
            - link: 
              - type: internalLink
              - uri: /docs/api # => http://dev.fiserv.com/docs/api
